name: expense_tracker
description: A smart expense tracking app with text recognition.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 本地存储
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  path: ^1.8.3

  # 状态管理
  provider: ^6.1.0

  # UI组件
  flutter_screenutil: ^5.9.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.6

  # 工具类
  uuid: ^4.0.0

  # 权限管理
  permission_handler: ^11.0.0

  # 文件操作和分享
  share_plus: ^7.2.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: PingFang
  #     fonts:
  #       - asset: assets/fonts/PingFang-Regular.ttf
